[profile.default]
src = "src"
out = "out"
libs = ["lib"]

eth_rpc_url = "https://rpc.sepolia.org"
etherscan_api_key = "${ETHERSCAN_KEY}"

[fuzz]
runs = 10_000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# remappings = [
#     "@openzeppelin-contracts/=lib/openzeppelin-contracts/",
# ]

